### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by keithkfng** [ImagicalMine/IM-iOS#1]
Mane you should base this on the Plug-PocketMine app available on the App Store XD

**Comment by applqpak** [comment]
What?

**Comment by keithkfng** [comment]
https://itunes.apple.com/au/app/plug-pocketmine-for-minecraft/id1030395486?mt=8

**Comment by applqpak** [comment]
Oh xD

**Comment by keithkfng** [comment]
LOL, you only realised?

**Comment by applqpak** [comment]
Erhm..... No... :P

**Comment by applqpak** [comment]
Have you got an icon you want me to use?

**Comment by InfornoFire** [comment]
Da, There was that the entire time, and they have not told us about it on the web. Not only that but they have not even updated the jailbreak version :P

**Comment by applqpak** [comment]
What?

**Comment by keithkfng** [comment]
Never mind XD

**Comment by applqpak** [comment]
Lol
