### ISSUE TITLE
So how do we remove it

### ISSUE THREAD

**Issue by InfornoFire** [ImagicalMine/IM-iOS#2]
Is there any way, jailbreak, a computer? anything?

**Comment by PocketKiller** [comment]
what do you mean?

**Comment by InfornoFire** [comment]
Says here, You cannot delete the profile or the app, Do you really think people would not have second thoughts on installing it? They do.

**Comment by legoboy0215** [comment]
You can delete it. Go to settings, profile.

**Comment by applqpak** [comment]
Exactly.

**Comment by applqpak** [comment]
Nevermind; I updated the app profile, just reinstall it and you'll be able to delete it.

**Comment by InfornoFire** [comment]
Thank you

**Comment by applqpak** [comment]
No worries :) thanks for making me notice this, lol
