### ISSUE TITLE
Profile is not Signed

### ISSUE THREAD

**Issue by jasonwynn10** [ImagicalMine/IM-iOS#3]
I just tried this... It gave me an error that it wasn't signed and that I wouldn't be able to remove it if I wanted to...

**Comment by keithkfng** [comment]
You can if you go to settings...

**Comment by jasonwynn10** [comment]
That wasn't my point... It should get signed and get an app icon

**Comment by applqpak** [comment]
It does not **_have to be_** signed.

**Comment by applqpak** [comment]
Plus, it is removable.

**Comment by jasonwynn10** [comment]
But if it were, it wouldn't give a warning message.

**Comment by applqpak** [comment]
Wait... Maybe the web server hasn't the update...

**Comment by applqpak** [comment]
Just checked: the update on the site wasn't updated. Try it now.

**Comment by applqpak** [comment]
BTW, having the profile signs and not signed really doesn't change anything.

**Comment by applqpak** [comment]
Signed*

**Comment by jasonwynn10** [comment]
The uninstall warning error is fixed

**Comment by applqpak** [comment]
Yep.
